### get all
GET http://127.0.0.1:3000/api/chat


### create new user
POST http://127.0.0.1:3000/createAccount
Content-Type: application/json; charset=utf-8

{
   "userName": "user88",
   "password": "Hejhopp12.",
   "email": "hej@mail.com"
 }  


### create new message
 POST http://127.0.0.1:3000/newMessage
 Content-Type: application/json; charset=utf-8

 {
  "userName": "Lisa",
   "text": "hejdå!"
 }

### get session
GET http://127.0.0.1:3000/session

### get all messages
GET http://127.0.0.1:3000/allMessages