### get all
GET http://127.0.0.1:3000/api/chat


### create new user
POST http://127.0.0.1:3000/createAccount
Content-Type: application/json; charset=utf-8

{
   "userName": "user6",
   "password": "hejhopp",
   "email": "hejdå"
 }